# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evacuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evacuatorID', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('lat', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('lng', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('currentCapacity', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('maxCapacity', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
