# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savior_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacuator',
            name='currentCapacity',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='evacuator',
            name='lat',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evacuator',
            name='lng',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evacuator',
            name='maxCapacity',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
